# Generated by Django 4.1 on 2022-08-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_rename_ads_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='is_published',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ad',
            name='name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.CharField(max_length=20),
        ),
    ]
