# Generated by Django 4.1 on 2022-08-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slag', models.SlugField()),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=2000)),
                ('price', models.IntegerField(max_length=20)),
                ('description', models.CharField(max_length=2000)),
                ('address', models.CharField(max_length=200)),
                ('is_published', models.CharField(choices=[('draft', 'черновик'), ('open', 'открыто'), ('closed', 'в архиве')], default='draft', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slag', models.SlugField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
