# Generated by Django 4.1 on 2022-08-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='slag',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='slag',
        ),
        migrations.AlterField(
            model_name='ads',
            name='is_published',
            field=models.DateField(auto_now_add=True),
        ),
    ]
